config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts, only: [:index, :new, :create, :show] do
    resources :comments, only: [:create]
  end

  match '/auth/:provider/callback', to: 'sessions#create', via: [:post, :get]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :content
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many   :comments

  validates_presence_of :content

  scope :newest_first, ->() { order(created_at: :desc) }
end

app/models/user.rb
class User < ActiveRecord::Base
  class_attribute :current_user

  def self.build_from_omniauth(auth_hash)
    user = self.new
    user.provider   = auth_hash.provider
    user.uid        = auth_hash.uid
    user.email      = auth_hash.info.email
    user.first_name = auth_hash.info.first_name
    user.last_name  = auth_hash.info.last_name
    user.full_name  = auth_hash.info.name
    user.domain     = domain_from_email(user.email)
    user
  end

  def self.find_or_create_from_omniauth(auth_hash)
    user = self.find_by_uid(auth_hash.uid)
    return user if user.present?

    user = self.build_from_omniauth(auth_hash)
    user.save!
    user
  end

  def self.domain_from_email(email)
    email.match(/@(.*)$/)[1] rescue nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :always_logged_in

  def always_logged_in
    if id = session[:current_user_id]
      User.current_user = User.find(id)
    else
      session[:after_login_path] = request.path
      redirect_to '/auth/google'
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :html

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = User.current_user

    if @comment.save
      respond_with @comment, location: @post
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < WebsocketRails::BaseController
  def authorize_channel
    if User.current_user
      accept_channel User.current_user
      WebsocketRails[:notifications].trigger(
        :joined, User.current_user.full_name)
    else
      deny_channel message: 'Authorization failed!'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :html

  def index
    @post    = Post.new
    @comment = Comment.new
    @posts   = Post.newest_first
  end

  def create
    @post = Post.new post_params
    @post.user = User.current_user
    if @post.save
      WebsocketRails[:notifications].trigger 'new_post', @post
      redirect_to action: :index
    else
      @posts = Post.newest_first
      render :index
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :always_logged_in

  def create
    user = User.find_or_create_from_omniauth(auth_hash)
    if user.present?
      session[:current_user_id] = user.id
    end
    redirect_to session[:after_login_path] || '/'
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gravatar_helper.rb
module GravatarHelper
  def gravatar(user, width=1)
    hash = Digest::MD5.hexdigest(user.email.downcase)
    image_tag "http://www.gravatar.com/avatar/#{hash}", class: "span-avatar#{width} avatar"
  end
end

app/views/comments/_comment.html.haml
.row.comment{ id: comment.id }
  = gravatar comment.user
  .span6.content
    %p.author= comment.user.full_name
    %p.comment-date
      = time_ago_in_words comment.created_at \
      = t('ago')
    = comment.content

app/views/layouts/application.html.haml
!!! 5
%html
  %head
  %title= t('.helaas')
  = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = csrf_meta_tags

  %body
    %button#toggle_notifications Notifications
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          = link_to t('.helaas'), root_path, class: 'brand'
          .nav-collapse.collapse
            %ul.nav
              %li= link_to t('.home'), root_path

    .container
      = yield

      #notifications{ 'data-uri' => "#{root_url(true).sub(/^http:\/\//, '')}websocket" }

app/views/posts/_form.html.haml
.well
  = simple_form_for @post do |f|
    = f.input :content, label: false, placeholder: t('.share_something')
    = f.button :submit, class: 'btn btn-primary pull-right'

app/views/posts/_post.html.haml
.post.row
  = gravatar(post.user, 2)
  .content.span9
    %p.author= post.user.full_name
    %p.post-date
      = time_ago_in_words post.created_at \
      = t('ago')
    = post.content
  .span2= link_to t('.read_more'), post

  .comments.span9.offset1
    = render post.comments
  .comment-form.span9
    = gravatar(User.current_user)
    .span7
      = simple_form_for [post, @comment] do |f|
        = f.input :content, label: false
        = f.button :submit

app/views/posts/index.html.haml
#posts
  %h3= t('.updates_in_your_network')

  = render 'form'

  = render @posts

  =link_to t('.new'), new_post_path, class: 'btn btn-primary btn-large'

app/views/posts/show.html.haml
%p= @post.content

%table.table
  %tr
    %th= t('.comment')
    = render @post.comments

= simple_form_for [@post, @comment] do |f|
  = f.input :content
  = f.button :submit